name: proumkm
description: Aplikasi untuk monitoring belanja pegawai ASN atau non ASN di Kota Madiun..

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+4

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter  
  # flutter_webview_plugin: ^0.3.11
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.4.0
  shared_preferences: ^2.0.11
  font_awesome_flutter: ^10.1.0
  file_picker: ^10.2.1
  intl: ^0.20.2
  webview_flutter: ^4.8.0
  webview_flutter_android: ^4.8.2
  adaptivex: ^0.0.1+6
  email_validator: ^3.0.0
  # validate: any
  table_calendar: ^3.0.6
  dotted_decoration: ^2.0.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  # flutter_animated_cards: any
  animated_card: ^2.0.0
  flutter_flip_card: ^0.0.4
  animated_flip_card: ^1.0.2
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  awesome_dialog: ^3.2.1
  url_launcher: ^6.0.20
  simple_animations: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon_login.png
    - assets/icon_login_putih.png
    - assets/icon_login_polos.png
    - assets/splash.gif
    - assets/icon_register.png
    - assets/noimage.png