<<<<<<< HEAD
name: proumkm
description: Aplikasi untuk monitoring belanja pegawai ASN atau non ASN di Kota Madiun..
=======
name: aplikasi_pertama
description: A new Flutter project.
>>>>>>> de63020cf17c5461bcacb016b0930b6d85cc7ab8

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

<<<<<<< HEAD

=======
>>>>>>> de63020cf17c5461bcacb016b0930b6d85cc7ab8
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter  
<<<<<<< HEAD
  # flutter_webview_plugin: ^0.3.11    
=======

    
>>>>>>> de63020cf17c5461bcacb016b0930b6d85cc7ab8
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.4
  shared_preferences: ^2.0.11
  font_awesome_flutter: ^10.1.0
  file_picker: ^5.2.5
  intl: ^0.18.0
<<<<<<< HEAD
  webview_flutter: any
  webview_flutter_android: ^3.6.0
  flutter_webview_plugin: any
  adaptivex: ^0.0.1+6
  email_validator: ^2.1.17
  # validate: any
  table_calendar: ^3.0.6
  dotted_decoration: ^2.0.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  # flutter_animated_cards: any
  animated_card: ^2.0.0
  flutter_flip_card: ^0.0.4
  animated_flip_card: ^1.0.2
  image_picker: ^0.8.8
 
=======
  adaptivex: ^0.0.1+6
  email_validator: ^2.1.17
  validate: ^1.7.0

>>>>>>> de63020cf17c5461bcacb016b0930b6d85cc7ab8
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
<<<<<<< HEAD
    - assets/icon_login.png
    - assets/splash.gif
    - assets/icon_register.png
=======
     - assets/
>>>>>>> de63020cf17c5461bcacb016b0930b6d85cc7ab8
 